fileFormatVersion: 2
guid: 74f140c827788b64ebde10a2197d3c0b
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 212563
  packageName: Edgegap Game Server & Hosting
  packageVersion: 3.0.9
  assetPath: Assets/FishNet/Plugins/Edgegap/Editor/Dockerfile
  uploadId: 715162
